name: CI/CD pipeline

on:
  push:
    branches:
      - master
jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

     
        
      - name: Build with mvn
        run: mvn clean package
        
            
        #Deploy WAR to Tomcat  
      - name: Deploy to tomcat
        run: |
               curl -v -u ${{secrets.TOMCAT_USER}}:${{secrets.TOMCAT_PASSWORD}} \
                  -T target/TrainBook-1.0.0-SNAPSHOT.war \
                   "http://${{secrets.TOMCAT_HOST}}:8080/manager/text/deploy?path=/TrainBook&update=true"

       #Deploy WAR to Tomcat  
      - name: Deploy to tomcat
        run: |
               curl -v -u ${{secrets.TOMCAT_USER_1}}:${{secrets.TOMCAT_PASSWORD_1}} \
                  -T target/TrainBook-1.0.0-SNAPSHOT.war \
                   "http://${{secrets.TOMCAT_HOST_1}}:8080/manager/text/deploy?path=/TrainBook&update=true"

                  
                  

                  
                  
     
